services:
  free-site:
    build: .
    container_name: free-site
    ports:
      - "3000:80"

  free-site-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: free-site-dev
    ports:
      - "5173:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    profiles:
      - dev
